# Book settings
title: "Quality Assurance of Code for Analysis and Research"
author: ""
email: gsshelp@statistics.gov.uk
logo: "./_static/duck_book_logo.svg"

repository:
  url: https://github.com/best-practice-and-impact/qa-of-code-guidance

html:
  home_page_in_navbar: false
  favicon: "./_static/favicon.ico"
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_footer: "<p>Best Practice & Impact division, Office for National Statistics</p><p>This document is very young, please help use to make it grow by providing any feedback by <a href='mailto:gsshelp@statistics.gov.uk'>email</a> or via the <a href='https://github.com/best-practice-and-impact/qa-of-code-guidance'>GitHub repository</a>."
  extra_navbar: "<p>Book version 2021.9</p><a href='https://www.gov.uk/government/organisations/government-analysis-function' target='_blank'><img src='./_static/af_logo.png' alt='The Government Analysis Function logo' style='width:50%;'></a>"

execute:
  stderr_output: show
#sphinx:
#  extra_extensions:
#    - sphinx_tabs.tabs
#    - sphinx.ext.todo
#  config:
#    todo_include_todos: true
#    language: en
#    html_show_copyright: false
sphinx:
  extra_extensions:
  - 'sphinx.ext.autodoc'
  - 'sphinx.ext.autosummary'
  - 'sphinx.ext.napoleon'
  config:
    autosummary_generate: True
    add_module_names: False
    templates_path: [_templates]
    
latex:
  latex_documents:
    targetname: book.tex
